# Generated by Django 2.0.13 on 2019-06-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('director_name', models.CharField(max_length=200)),
            ],
        ),
    ]
