# Generated by Django 2.0.13 on 2019-06-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
