# Generated by Django 2.0.13 on 2019-06-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_movie_movie_imdb_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('PH', 'Philippines'), ('CH', 'Chile'), ('TH', 'Thailand'), ('NI', 'Nigeria'), ('CO', 'Colombia'), ('KY', 'Kyrgyzstan'), ('SP', 'Spain'), ('US', 'USA'), ('BE', 'Belgium'), ('ME', 'Mexico'), ('SO', 'Soviet Union'), ('NE', 'Netherlands'), ('GR', 'Greece'), ('TA', 'Taiwan'), ('PA', 'Pakistan'), ('AU', 'Australia'), ('IR', 'Ireland'), ('KE', 'Kenya'), ('IT', 'Italy'), ('TU', 'Turkey'), ('DE', 'Denmark'), ('FR', 'France'), ('CA', 'Canada'), ('SL', 'Slovenia'), ('NE', 'New Zealand'), ('GE', 'Germany'), ('AF', 'Afghanistan'), ('RO', 'Romania'), ('OF', 'Official site'), ('CZ', 'Czech Republic'), ('SL', 'Slovakia'), ('IS', 'Israel'), ('EG', 'Egypt'), ('IN', 'Indonesia'), ('BA', 'Bahamas'), ('AR', 'Argentina'), ('LI', 'Libya'), ('IC', 'Iceland'), ('JA', 'Japan'), ('SW', 'Switzerland'), ('IR', 'Iran'), ('CH', 'China'), ('BR', 'Brazil'), ('FI', 'Finland'), ('SO', 'South Africa'), ('SO', 'South Korea'), ('CA', 'Cambodia'), ('RU', 'Russia'), ('DO', 'Dominican Republic'), ('PO', 'Poland'), ('BU', 'Bulgaria'), ('PA', 'Panama'), ('HU', 'Hungary'), ('IN', 'India'), ('GE', 'Georgia'), ('UK', 'UK'), ('SW', 'Sweden'), ('UN', 'United Arab Emirates'), ('WE', 'West Germany'), ('AR', 'Aruba'), ('HO', 'Hong Kong'), ('NE', 'New Line'), ('CA', 'Cameroon'), ('NO', 'Norway'), ('PE', 'Peru')], max_length=2, null=True),
        ),
    ]
