# Generated by Django 2.0.13 on 2019-06-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_movie_movie_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_aspect_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_color',
            field=models.CharField(choices=[('C', 'Color'), ('BW', 'Black And White')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_facebook_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_gross',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_imdb_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('KAZ', 'Kazakh'), ('TEL', 'Telugu'), ('FIL', 'Filipino'), ('CZE', 'Czech'), ('ABO', 'Aboriginal'), ('ARA', 'Aramaic'), ('SLO', 'Slovenian'), ('ZUL', 'Zulu'), ('JAP', 'Japanese'), ('DZO', 'Dzongkha'), ('ICE', 'Icelandic'), ('SWE', 'Swedish'), ('PER', 'Persian'), ('GRE', 'Greek'), ('MAN', 'Mandarin'), ('DAR', 'Dari'), ('HEB', 'Hebrew'), ('CAN', 'Cantonese'), ('HUN', 'Hungarian'), ('SPA', 'Spanish'), ('POL', 'Polish'), ('BOS', 'Bosnian'), ('GER', 'German'), ('POR', 'Portuguese'), ('KAN', 'Kannada'), ('PAN', 'Panjabi'), ('NON', 'None'), ('DAN', 'Danish'), ('ROM', 'Romanian'), ('THA', 'Thai'), ('HIN', 'Hindi'), ('MAY', 'Maya'), ('ITA', 'Italian'), ('SWA', 'Swahili'), ('MON', 'Mongolian'), ('NOR', 'Norwegian'), ('DUT', 'Dutch'), ('ENG', 'English'), ('VIE', 'Vietnamese'), ('IND', 'Indonesian'), ('CHI', 'Chinese'), ('RUS', 'Russian'), ('KOR', 'Korean'), ('ARA', 'Arabic'), ('URD', 'Urdu'), ('TAM', 'Tamil'), ('FRE', 'French')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_num_voted_users',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('KY', 'Kyrgyzstan'), ('NE', 'New Zealand'), ('BE', 'Belgium'), ('HU', 'Hungary'), ('CA', 'Cambodia'), ('ME', 'Mexico'), ('SO', 'Soviet Union'), ('SO', 'South Korea'), ('GE', 'Georgia'), ('FI', 'Finland'), ('NI', 'Nigeria'), ('IN', 'Indonesia'), ('PE', 'Peru'), ('TU', 'Turkey'), ('SW', 'Switzerland'), ('BR', 'Brazil'), ('CH', 'China'), ('OF', 'Official site'), ('CA', 'Cameroon'), ('LI', 'Libya'), ('FR', 'France'), ('RU', 'Russia'), ('IN', 'India'), ('AR', 'Argentina'), ('SW', 'Sweden'), ('SP', 'Spain'), ('PO', 'Poland'), ('AF', 'Afghanistan'), ('CO', 'Colombia'), ('UN', 'United Arab Emirates'), ('PH', 'Philippines'), ('PA', 'Pakistan'), ('CA', 'Canada'), ('IT', 'Italy'), ('AU', 'Australia'), ('IC', 'Iceland'), ('NO', 'Norway'), ('PA', 'Panama'), ('RO', 'Romania'), ('TA', 'Taiwan'), ('CZ', 'Czech Republic'), ('BU', 'Bulgaria'), ('SO', 'South Africa'), ('AR', 'Aruba'), ('KE', 'Kenya'), ('IR', 'Ireland'), ('GR', 'Greece'), ('NE', 'New Line'), ('US', 'USA'), ('EG', 'Egypt'), ('HO', 'Hong Kong'), ('WE', 'West Germany'), ('GE', 'Germany'), ('BA', 'Bahamas'), ('IS', 'Israel'), ('SL', 'Slovakia'), ('SL', 'Slovenia'), ('UK', 'UK'), ('NE', 'Netherlands'), ('IR', 'Iran'), ('TH', 'Thailand'), ('DO', 'Dominican Republic'), ('DE', 'Denmark'), ('JA', 'Japan'), ('CH', 'Chile')], max_length=2, null=True),
        ),
    ]
