# Generated by Django 2.0.13 on 2019-06-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0007_auto_20190615_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('NO', 'Norway'), ('IN', 'India'), ('UK', 'UK'), ('PE', 'Peru'), ('DE', 'Denmark'), ('WE', 'West Germany'), ('HU', 'Hungary'), ('GR', 'Greece'), ('IR', 'Ireland'), ('TH', 'Thailand'), ('FI', 'Finland'), ('IS', 'Israel'), ('IN', 'Indonesia'), ('FR', 'France'), ('AR', 'Aruba'), ('KE', 'Kenya'), ('SO', 'South Africa'), ('IC', 'Iceland'), ('KY', 'Kyrgyzstan'), ('GE', 'Germany'), ('SW', 'Sweden'), ('IR', 'Iran'), ('JA', 'Japan'), ('IT', 'Italy'), ('LI', 'Libya'), ('AU', 'Australia'), ('OF', 'Official site'), ('TA', 'Taiwan'), ('RU', 'Russia'), ('SO', 'South Korea'), ('CA', 'Canada'), ('TU', 'Turkey'), ('CA', 'Cameroon'), ('BE', 'Belgium'), ('SP', 'Spain'), ('SL', 'Slovenia'), ('AF', 'Afghanistan'), ('NI', 'Nigeria'), ('AR', 'Argentina'), ('CH', 'China'), ('EG', 'Egypt'), ('PA', 'Panama'), ('CZ', 'Czech Republic'), ('CA', 'Cambodia'), ('SL', 'Slovakia'), ('RO', 'Romania'), ('BU', 'Bulgaria'), ('GE', 'Georgia'), ('SW', 'Switzerland'), ('NE', 'Netherlands'), ('BR', 'Brazil'), ('PA', 'Pakistan'), ('DO', 'Dominican Republic'), ('SO', 'Soviet Union'), ('US', 'USA'), ('BA', 'Bahamas'), ('UN', 'United Arab Emirates'), ('NE', 'New Zealand'), ('NE', 'New Line'), ('CH', 'Chile'), ('PO', 'Poland'), ('CO', 'Colombia'), ('PH', 'Philippines'), ('HO', 'Hong Kong'), ('ME', 'Mexico')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('ARA', 'Arabic'), ('BOS', 'Bosnian'), ('PER', 'Persian'), ('MAN', 'Mandarin'), ('MON', 'Mongolian'), ('KAN', 'Kannada'), ('PAN', 'Panjabi'), ('CZE', 'Czech'), ('GRE', 'Greek'), ('FIL', 'Filipino'), ('ABO', 'Aboriginal'), ('SWE', 'Swedish'), ('TAM', 'Tamil'), ('SLO', 'Slovenian'), ('ICE', 'Icelandic'), ('JAP', 'Japanese'), ('ENG', 'English'), ('ROM', 'Romanian'), ('DZO', 'Dzongkha'), ('HEB', 'Hebrew'), ('TEL', 'Telugu'), ('VIE', 'Vietnamese'), ('SWA', 'Swahili'), ('DUT', 'Dutch'), ('FRE', 'French'), ('POR', 'Portuguese'), ('DAN', 'Danish'), ('NOR', 'Norwegian'), ('KAZ', 'Kazakh'), ('HUN', 'Hungarian'), ('RUS', 'Russian'), ('URD', 'Urdu'), ('KOR', 'Korean'), ('CAN', 'Cantonese'), ('HIN', 'Hindi'), ('THA', 'Thai'), ('ZUL', 'Zulu'), ('ARA', 'Aramaic'), ('IND', 'Indonesian'), ('NON', 'None'), ('DAR', 'Dari'), ('ITA', 'Italian'), ('GER', 'German'), ('SPA', 'Spanish'), ('POL', 'Polish'), ('CHI', 'Chinese'), ('MAY', 'Maya')], max_length=2, null=True),
        ),
    ]
