# Generated by Django 2.0.13 on 2019-06-16 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_auto_20190615_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_director_facebook_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_director_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.Director'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('SL', 'Slovenia'), ('AR', 'Argentina'), ('NE', 'New Line'), ('UN', 'United Arab Emirates'), ('SL', 'Slovakia'), ('IC', 'Iceland'), ('IR', 'Iran'), ('SO', 'South Korea'), ('NO', 'Norway'), ('US', 'USA'), ('SP', 'Spain'), ('BA', 'Bahamas'), ('CO', 'Colombia'), ('CA', 'Canada'), ('IN', 'India'), ('AR', 'Aruba'), ('FI', 'Finland'), ('SO', 'South Africa'), ('HU', 'Hungary'), ('RO', 'Romania'), ('JA', 'Japan'), ('TA', 'Taiwan'), ('SW', 'Sweden'), ('IR', 'Ireland'), ('CA', 'Cambodia'), ('PE', 'Peru'), ('NE', 'Netherlands'), ('IS', 'Israel'), ('GE', 'Georgia'), ('BR', 'Brazil'), ('KY', 'Kyrgyzstan'), ('PA', 'Pakistan'), ('DO', 'Dominican Republic'), ('CA', 'Cameroon'), ('ME', 'Mexico'), ('LI', 'Libya'), ('CH', 'China'), ('FR', 'France'), ('PH', 'Philippines'), ('BU', 'Bulgaria'), ('IT', 'Italy'), ('HO', 'Hong Kong'), ('SW', 'Switzerland'), ('GR', 'Greece'), ('OF', 'Official site'), ('KE', 'Kenya'), ('NE', 'New Zealand'), ('NI', 'Nigeria'), ('GE', 'Germany'), ('AU', 'Australia'), ('AF', 'Afghanistan'), ('PO', 'Poland'), ('CH', 'Chile'), ('RU', 'Russia'), ('SO', 'Soviet Union'), ('TH', 'Thailand'), ('WE', 'West Germany'), ('PA', 'Panama'), ('UK', 'UK'), ('TU', 'Turkey'), ('IN', 'Indonesia'), ('BE', 'Belgium'), ('CZ', 'Czech Republic'), ('EG', 'Egypt'), ('DE', 'Denmark')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('KAN', 'Kannada'), ('HIN', 'Hindi'), ('POR', 'Portuguese'), ('DZO', 'Dzongkha'), ('SPA', 'Spanish'), ('ROM', 'Romanian'), ('PER', 'Persian'), ('ABO', 'Aboriginal'), ('CAN', 'Cantonese'), ('ICE', 'Icelandic'), ('POL', 'Polish'), ('ZUL', 'Zulu'), ('SWE', 'Swedish'), ('TEL', 'Telugu'), ('MAN', 'Mandarin'), ('SLO', 'Slovenian'), ('CHI', 'Chinese'), ('KAZ', 'Kazakh'), ('THA', 'Thai'), ('RUS', 'Russian'), ('BOS', 'Bosnian'), ('ITA', 'Italian'), ('VIE', 'Vietnamese'), ('SWA', 'Swahili'), ('HEB', 'Hebrew'), ('MAY', 'Maya'), ('URD', 'Urdu'), ('ARA', 'Aramaic'), ('HUN', 'Hungarian'), ('DUT', 'Dutch'), ('DAN', 'Danish'), ('JAP', 'Japanese'), ('ENG', 'English'), ('MON', 'Mongolian'), ('GER', 'German'), ('FRE', 'French'), ('NON', 'None'), ('ARA', 'Arabic'), ('NOR', 'Norwegian'), ('DAR', 'Dari'), ('KOR', 'Korean'), ('PAN', 'Panjabi'), ('CZE', 'Czech'), ('TAM', 'Tamil'), ('GRE', 'Greek'), ('FIL', 'Filipino'), ('IND', 'Indonesian')], max_length=2, null=True),
        ),
    ]
