# Generated by Django 2.0.13 on 2019-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0009_auto_20190615_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('IR', 'Ireland'), ('UK', 'UK'), ('OF', 'Official site'), ('SO', 'South Africa'), ('SW', 'Switzerland'), ('ME', 'Mexico'), ('CA', 'Canada'), ('WE', 'West Germany'), ('BU', 'Bulgaria'), ('US', 'USA'), ('SL', 'Slovenia'), ('IS', 'Israel'), ('HO', 'Hong Kong'), ('SW', 'Sweden'), ('CA', 'Cameroon'), ('AU', 'Australia'), ('GE', 'Germany'), ('CO', 'Colombia'), ('SO', 'South Korea'), ('NE', 'Netherlands'), ('SO', 'Soviet Union'), ('CH', 'Chile'), ('IN', 'India'), ('PO', 'Poland'), ('FI', 'Finland'), ('IC', 'Iceland'), ('EG', 'Egypt'), ('AF', 'Afghanistan'), ('GR', 'Greece'), ('GE', 'Georgia'), ('KE', 'Kenya'), ('HU', 'Hungary'), ('FR', 'France'), ('BE', 'Belgium'), ('PE', 'Peru'), ('NO', 'Norway'), ('NI', 'Nigeria'), ('RU', 'Russia'), ('TH', 'Thailand'), ('JA', 'Japan'), ('SL', 'Slovakia'), ('PH', 'Philippines'), ('NE', 'New Zealand'), ('RO', 'Romania'), ('IR', 'Iran'), ('BR', 'Brazil'), ('BA', 'Bahamas'), ('TA', 'Taiwan'), ('IN', 'Indonesia'), ('DO', 'Dominican Republic'), ('DE', 'Denmark'), ('CH', 'China'), ('CZ', 'Czech Republic'), ('AR', 'Argentina'), ('PA', 'Pakistan'), ('IT', 'Italy'), ('PA', 'Panama'), ('AR', 'Aruba'), ('SP', 'Spain'), ('LI', 'Libya'), ('CA', 'Cambodia'), ('TU', 'Turkey'), ('UN', 'United Arab Emirates'), ('NE', 'New Line'), ('KY', 'Kyrgyzstan')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('MAN', 'Mandarin'), ('ABO', 'Aboriginal'), ('HIN', 'Hindi'), ('CZE', 'Czech'), ('POR', 'Portuguese'), ('ARA', 'Arabic'), ('FIL', 'Filipino'), ('HEB', 'Hebrew'), ('ARA', 'Aramaic'), ('CHI', 'Chinese'), ('RUS', 'Russian'), ('CAN', 'Cantonese'), ('DAR', 'Dari'), ('GER', 'German'), ('MON', 'Mongolian'), ('SLO', 'Slovenian'), ('JAP', 'Japanese'), ('SPA', 'Spanish'), ('THA', 'Thai'), ('ITA', 'Italian'), ('BOS', 'Bosnian'), ('KAN', 'Kannada'), ('TEL', 'Telugu'), ('POL', 'Polish'), ('DAN', 'Danish'), ('SWE', 'Swedish'), ('ROM', 'Romanian'), ('NON', 'None'), ('MAY', 'Maya'), ('ZUL', 'Zulu'), ('FRE', 'French'), ('GRE', 'Greek'), ('ENG', 'English'), ('VIE', 'Vietnamese'), ('TAM', 'Tamil'), ('NOR', 'Norwegian'), ('KAZ', 'Kazakh'), ('PAN', 'Panjabi'), ('SWA', 'Swahili'), ('ICE', 'Icelandic'), ('IND', 'Indonesian'), ('DZO', 'Dzongkha'), ('URD', 'Urdu'), ('DUT', 'Dutch'), ('HUN', 'Hungarian'), ('PER', 'Persian'), ('KOR', 'Korean')], max_length=2, null=True),
        ),
    ]
