# Generated by Django 2.0.13 on 2019-06-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_auto_20190616_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('AR', 'Argentina'), ('NO', 'Norway'), ('AU', 'Australia'), ('SP', 'Spain'), ('NE', 'Netherlands'), ('PH', 'Philippines'), ('OF', 'Official site'), ('NE', 'New Line'), ('EG', 'Egypt'), ('SW', 'Switzerland'), ('DO', 'Dominican Republic'), ('IR', 'Ireland'), ('NE', 'New Zealand'), ('CO', 'Colombia'), ('IS', 'Israel'), ('KE', 'Kenya'), ('JA', 'Japan'), ('US', 'USA'), ('PE', 'Peru'), ('RO', 'Romania'), ('AF', 'Afghanistan'), ('CA', 'Canada'), ('WE', 'West Germany'), ('UN', 'United Arab Emirates'), ('CH', 'Chile'), ('SO', 'Soviet Union'), ('IT', 'Italy'), ('GR', 'Greece'), ('RU', 'Russia'), ('SW', 'Sweden'), ('BR', 'Brazil'), ('IR', 'Iran'), ('FI', 'Finland'), ('PO', 'Poland'), ('NI', 'Nigeria'), ('SL', 'Slovenia'), ('GE', 'Germany'), ('IC', 'Iceland'), ('IN', 'Indonesia'), ('SO', 'South Africa'), ('TU', 'Turkey'), ('KY', 'Kyrgyzstan'), ('CH', 'China'), ('BE', 'Belgium'), ('ME', 'Mexico'), ('TH', 'Thailand'), ('LI', 'Libya'), ('AR', 'Aruba'), ('DE', 'Denmark'), ('SO', 'South Korea'), ('TA', 'Taiwan'), ('GE', 'Georgia'), ('BA', 'Bahamas'), ('BU', 'Bulgaria'), ('PA', 'Pakistan'), ('CZ', 'Czech Republic'), ('FR', 'France'), ('PA', 'Panama'), ('CA', 'Cambodia'), ('IN', 'India'), ('HO', 'Hong Kong'), ('CA', 'Cameroon'), ('UK', 'UK'), ('HU', 'Hungary'), ('SL', 'Slovakia')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('RUS', 'Russian'), ('CZE', 'Czech'), ('SWA', 'Swahili'), ('ZUL', 'Zulu'), ('TEL', 'Telugu'), ('TAM', 'Tamil'), ('CHI', 'Chinese'), ('IND', 'Indonesian'), ('ICE', 'Icelandic'), ('VIE', 'Vietnamese'), ('HUN', 'Hungarian'), ('THA', 'Thai'), ('NON', 'None'), ('URD', 'Urdu'), ('CAN', 'Cantonese'), ('SPA', 'Spanish'), ('KAN', 'Kannada'), ('MON', 'Mongolian'), ('DZO', 'Dzongkha'), ('ENG', 'English'), ('ROM', 'Romanian'), ('PAN', 'Panjabi'), ('FIL', 'Filipino'), ('ARA', 'Arabic'), ('GER', 'German'), ('DUT', 'Dutch'), ('POR', 'Portuguese'), ('ARA', 'Aramaic'), ('HEB', 'Hebrew'), ('DAN', 'Danish'), ('POL', 'Polish'), ('GRE', 'Greek'), ('MAN', 'Mandarin'), ('ITA', 'Italian'), ('FRE', 'French'), ('JAP', 'Japanese'), ('HIN', 'Hindi'), ('DAR', 'Dari'), ('SWE', 'Swedish'), ('KOR', 'Korean'), ('MAY', 'Maya'), ('KAZ', 'Kazakh'), ('ABO', 'Aboriginal'), ('SLO', 'Slovenian'), ('NOR', 'Norwegian'), ('PER', 'Persian'), ('BOS', 'Bosnian')], max_length=2, null=True),
        ),
    ]
