# Generated by Django 2.0.13 on 2019-06-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_auto_20190616_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('CO', 'Colombia'), ('SO', 'South Korea'), ('UN', 'United Arab Emirates'), ('CH', 'Chile'), ('SO', 'South Africa'), ('PO', 'Poland'), ('AR', 'Argentina'), ('US', 'USA'), ('CA', 'Cameroon'), ('IR', 'Ireland'), ('IN', 'Indonesia'), ('KE', 'Kenya'), ('GE', 'Georgia'), ('AU', 'Australia'), ('EG', 'Egypt'), ('ME', 'Mexico'), ('NE', 'New Zealand'), ('LI', 'Libya'), ('BU', 'Bulgaria'), ('IN', 'India'), ('SW', 'Sweden'), ('PH', 'Philippines'), ('RO', 'Romania'), ('RU', 'Russia'), ('CA', 'Canada'), ('IC', 'Iceland'), ('SL', 'Slovakia'), ('HO', 'Hong Kong'), ('TA', 'Taiwan'), ('DO', 'Dominican Republic'), ('SO', 'Soviet Union'), ('AF', 'Afghanistan'), ('CH', 'China'), ('NI', 'Nigeria'), ('JA', 'Japan'), ('SW', 'Switzerland'), ('CZ', 'Czech Republic'), ('TU', 'Turkey'), ('CA', 'Cambodia'), ('TH', 'Thailand'), ('HU', 'Hungary'), ('SP', 'Spain'), ('PE', 'Peru'), ('PA', 'Panama'), ('IR', 'Iran'), ('FI', 'Finland'), ('NE', 'Netherlands'), ('BA', 'Bahamas'), ('BR', 'Brazil'), ('IS', 'Israel'), ('KY', 'Kyrgyzstan'), ('IT', 'Italy'), ('WE', 'West Germany'), ('GR', 'Greece'), ('FR', 'France'), ('NO', 'Norway'), ('SL', 'Slovenia'), ('UK', 'UK'), ('BE', 'Belgium'), ('DE', 'Denmark'), ('GE', 'Germany'), ('PA', 'Pakistan'), ('NE', 'New Line'), ('OF', 'Official site'), ('AR', 'Aruba')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('KOR', 'Korean'), ('MAY', 'Maya'), ('SPA', 'Spanish'), ('IND', 'Indonesian'), ('POL', 'Polish'), ('ABO', 'Aboriginal'), ('VIE', 'Vietnamese'), ('JAP', 'Japanese'), ('RUS', 'Russian'), ('DZO', 'Dzongkha'), ('MON', 'Mongolian'), ('KAZ', 'Kazakh'), ('GRE', 'Greek'), ('SWA', 'Swahili'), ('DUT', 'Dutch'), ('NOR', 'Norwegian'), ('ENG', 'English'), ('ITA', 'Italian'), ('CZE', 'Czech'), ('PER', 'Persian'), ('CHI', 'Chinese'), ('SWE', 'Swedish'), ('DAN', 'Danish'), ('TEL', 'Telugu'), ('FRE', 'French'), ('POR', 'Portuguese'), ('SLO', 'Slovenian'), ('ICE', 'Icelandic'), ('HEB', 'Hebrew'), ('HIN', 'Hindi'), ('ARA', 'Arabic'), ('TAM', 'Tamil'), ('ZUL', 'Zulu'), ('ARA', 'Aramaic'), ('ROM', 'Romanian'), ('HUN', 'Hungarian'), ('MAN', 'Mandarin'), ('FIL', 'Filipino'), ('GER', 'German'), ('THA', 'Thai'), ('DAR', 'Dari'), ('PAN', 'Panjabi'), ('URD', 'Urdu'), ('CAN', 'Cantonese'), ('BOS', 'Bosnian'), ('KAN', 'Kannada'), ('NON', 'None')], max_length=200, null=True),
        ),
    ]
