# Generated by Django 2.0.13 on 2019-06-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_auto_20190616_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('CA', 'Canada'), ('DO', 'Dominican Republic'), ('UK', 'UK'), ('CH', 'China'), ('NE', 'New Line'), ('SO', 'South Korea'), ('TH', 'Thailand'), ('KY', 'Kyrgyzstan'), ('SP', 'Spain'), ('IN', 'Indonesia'), ('KE', 'Kenya'), ('SO', 'South Africa'), ('AR', 'Argentina'), ('CH', 'Chile'), ('CZ', 'Czech Republic'), ('JA', 'Japan'), ('IN', 'India'), ('HO', 'Hong Kong'), ('PA', 'Panama'), ('FR', 'France'), ('IR', 'Iran'), ('FI', 'Finland'), ('US', 'USA'), ('BR', 'Brazil'), ('IS', 'Israel'), ('AU', 'Australia'), ('SO', 'Soviet Union'), ('IC', 'Iceland'), ('IR', 'Ireland'), ('AF', 'Afghanistan'), ('HU', 'Hungary'), ('PO', 'Poland'), ('AR', 'Aruba'), ('GR', 'Greece'), ('RO', 'Romania'), ('NI', 'Nigeria'), ('NE', 'New Zealand'), ('SL', 'Slovakia'), ('ME', 'Mexico'), ('UN', 'United Arab Emirates'), ('SW', 'Switzerland'), ('TA', 'Taiwan'), ('GE', 'Georgia'), ('RU', 'Russia'), ('OF', 'Official site'), ('NE', 'Netherlands'), ('TU', 'Turkey'), ('EG', 'Egypt'), ('WE', 'West Germany'), ('NO', 'Norway'), ('LI', 'Libya'), ('BA', 'Bahamas'), ('PH', 'Philippines'), ('BU', 'Bulgaria'), ('CA', 'Cambodia'), ('PA', 'Pakistan'), ('PE', 'Peru'), ('IT', 'Italy'), ('DE', 'Denmark'), ('GE', 'Germany'), ('SL', 'Slovenia'), ('BE', 'Belgium'), ('SW', 'Sweden'), ('CA', 'Cameroon'), ('CO', 'Colombia')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('CZE', 'Czech'), ('DAR', 'Dari'), ('VIE', 'Vietnamese'), ('KOR', 'Korean'), ('KAN', 'Kannada'), ('GRE', 'Greek'), ('SPA', 'Spanish'), ('CAN', 'Cantonese'), ('ZUL', 'Zulu'), ('DUT', 'Dutch'), ('NOR', 'Norwegian'), ('IND', 'Indonesian'), ('URD', 'Urdu'), ('PAN', 'Panjabi'), ('GER', 'German'), ('ARA', 'Aramaic'), ('RUS', 'Russian'), ('THA', 'Thai'), ('HIN', 'Hindi'), ('HEB', 'Hebrew'), ('PER', 'Persian'), ('TEL', 'Telugu'), ('ARA', 'Arabic'), ('SWE', 'Swedish'), ('SWA', 'Swahili'), ('ABO', 'Aboriginal'), ('MAY', 'Maya'), ('CHI', 'Chinese'), ('TAM', 'Tamil'), ('ENG', 'English'), ('POR', 'Portuguese'), ('JAP', 'Japanese'), ('KAZ', 'Kazakh'), ('SLO', 'Slovenian'), ('NON', 'None'), ('HUN', 'Hungarian'), ('FRE', 'French'), ('MON', 'Mongolian'), ('DZO', 'Dzongkha'), ('ROM', 'Romanian'), ('POL', 'Polish'), ('DAN', 'Danish'), ('ITA', 'Italian'), ('ICE', 'Icelandic'), ('FIL', 'Filipino'), ('BOS', 'Bosnian'), ('MAN', 'Mandarin')], max_length=200, null=True),
        ),
    ]
