# Generated by Django 2.0.13 on 2019-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0014_auto_20190616_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('FI', 'Finland'), ('NE', 'New Zealand'), ('UK', 'UK'), ('SO', 'South Africa'), ('GR', 'Greece'), ('DO', 'Dominican Republic'), ('CA', 'Canada'), ('WE', 'West Germany'), ('TA', 'Taiwan'), ('TH', 'Thailand'), ('TU', 'Turkey'), ('CA', 'Cameroon'), ('KE', 'Kenya'), ('PH', 'Philippines'), ('SW', 'Sweden'), ('SW', 'Switzerland'), ('BU', 'Bulgaria'), ('SO', 'Soviet Union'), ('HO', 'Hong Kong'), ('US', 'USA'), ('UN', 'United Arab Emirates'), ('BE', 'Belgium'), ('NO', 'Norway'), ('AR', 'Argentina'), ('IR', 'Iran'), ('IN', 'Indonesia'), ('IS', 'Israel'), ('IT', 'Italy'), ('CO', 'Colombia'), ('PA', 'Panama'), ('SL', 'Slovakia'), ('AU', 'Australia'), ('KY', 'Kyrgyzstan'), ('RU', 'Russia'), ('IC', 'Iceland'), ('GE', 'Georgia'), ('LI', 'Libya'), ('ME', 'Mexico'), ('OF', 'Official site'), ('IR', 'Ireland'), ('BA', 'Bahamas'), ('PA', 'Pakistan'), ('AF', 'Afghanistan'), ('JA', 'Japan'), ('SO', 'South Korea'), ('SL', 'Slovenia'), ('CZ', 'Czech Republic'), ('DE', 'Denmark'), ('NI', 'Nigeria'), ('CH', 'Chile'), ('HU', 'Hungary'), ('NE', 'Netherlands'), ('AR', 'Aruba'), ('GE', 'Germany'), ('IN', 'India'), ('RO', 'Romania'), ('CA', 'Cambodia'), ('EG', 'Egypt'), ('CH', 'China'), ('PO', 'Poland'), ('FR', 'France'), ('NE', 'New Line'), ('SP', 'Spain'), ('BR', 'Brazil'), ('PE', 'Peru')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(choices=[('POR', 'Portuguese'), ('FRE', 'French'), ('CAN', 'Cantonese'), ('GRE', 'Greek'), ('JAP', 'Japanese'), ('SWE', 'Swedish'), ('RUS', 'Russian'), ('CHI', 'Chinese'), ('ICE', 'Icelandic'), ('DAR', 'Dari'), ('MON', 'Mongolian'), ('KOR', 'Korean'), ('HUN', 'Hungarian'), ('URD', 'Urdu'), ('MAN', 'Mandarin'), ('GER', 'German'), ('TEL', 'Telugu'), ('DAN', 'Danish'), ('ITA', 'Italian'), ('HEB', 'Hebrew'), ('THA', 'Thai'), ('ABO', 'Aboriginal'), ('SWA', 'Swahili'), ('FIL', 'Filipino'), ('ZUL', 'Zulu'), ('DZO', 'Dzongkha'), ('ENG', 'English'), ('ROM', 'Romanian'), ('BOS', 'Bosnian'), ('PAN', 'Panjabi'), ('ARA', 'Arabic'), ('NON', 'None'), ('ARA', 'Aramaic'), ('HIN', 'Hindi'), ('MAY', 'Maya'), ('PER', 'Persian'), ('NOR', 'Norwegian'), ('SLO', 'Slovenian'), ('CZE', 'Czech'), ('KAZ', 'Kazakh'), ('KAN', 'Kannada'), ('TAM', 'Tamil'), ('POL', 'Polish'), ('SPA', 'Spanish'), ('VIE', 'Vietnamese'), ('IND', 'Indonesian'), ('DUT', 'Dutch')], max_length=200, null=True),
        ),
    ]
