# Generated by Django 2.0.13 on 2019-06-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0016_auto_20190617_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id_language', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(choices=[('SL', 'Slovenia'), ('UK', 'UK'), ('CA', 'Canada'), ('TH', 'Thailand'), ('EG', 'Egypt'), ('IR', 'Iran'), ('AF', 'Afghanistan'), ('SW', 'Switzerland'), ('BR', 'Brazil'), ('FI', 'Finland'), ('SW', 'Sweden'), ('PA', 'Pakistan'), ('AU', 'Australia'), ('PH', 'Philippines'), ('CO', 'Colombia'), ('SP', 'Spain'), ('KY', 'Kyrgyzstan'), ('AR', 'Aruba'), ('HU', 'Hungary'), ('IC', 'Iceland'), ('NI', 'Nigeria'), ('IN', 'Indonesia'), ('JA', 'Japan'), ('PO', 'Poland'), ('IR', 'Ireland'), ('IN', 'India'), ('LI', 'Libya'), ('AR', 'Argentina'), ('NE', 'New Zealand'), ('BE', 'Belgium'), ('FR', 'France'), ('NE', 'New Line'), ('RU', 'Russia'), ('NO', 'Norway'), ('SO', 'Soviet Union'), ('RO', 'Romania'), ('IS', 'Israel'), ('TU', 'Turkey'), ('GE', 'Georgia'), ('US', 'USA'), ('HO', 'Hong Kong'), ('CZ', 'Czech Republic'), ('DE', 'Denmark'), ('CH', 'China'), ('SO', 'South Korea'), ('IT', 'Italy'), ('SL', 'Slovakia'), ('DO', 'Dominican Republic'), ('GR', 'Greece'), ('CH', 'Chile'), ('PA', 'Panama'), ('ME', 'Mexico'), ('SO', 'South Africa'), ('WE', 'West Germany'), ('NE', 'Netherlands'), ('OF', 'Official site'), ('BA', 'Bahamas'), ('BU', 'Bulgaria'), ('UN', 'United Arab Emirates'), ('GE', 'Germany'), ('KE', 'Kenya'), ('CA', 'Cameroon'), ('CA', 'Cambodia'), ('PE', 'Peru'), ('TA', 'Taiwan')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_imdb_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
