# Generated by Django 2.0.13 on 2019-06-19 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0017_auto_20190618_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Country'),
        ),
    ]
