# Generated by Django 2.0.13 on 2019-06-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0018_auto_20190618_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_country',
        ),
    ]
