# Generated by Django 2.0.13 on 2019-06-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0019_remove_movie_movie_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
