# Generated by Django 2.0.13 on 2019-06-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0020_auto_20190618_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id_language', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=200)),
            ],
        ),
    ]
