# Generated by Django 2.0.13 on 2019-06-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0021_country_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.Country'),
            preserve_default=False,
        ),
    ]
