# Generated by Django 2.0.13 on 2019-06-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0022_movie_movie_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.Language'),
            preserve_default=False,
        ),
    ]
