# Generated by Django 2.0.13 on 2019-06-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0023_movie_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
