# Generated by Django 2.0.13 on 2019-06-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0024_auto_20190618_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_budget',
            field=models.BigIntegerField(),
        ),
    ]
