# Generated by Django 2.0.13 on 2019-06-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0025_auto_20190618_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_aspect_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_director_facebook_likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_facebook_likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_gross',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_imdb_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_num_voted_users',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
