# Generated by Django 2.0.13 on 2019-06-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0028_movie_movie_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Movies.Color'),
            preserve_default=False,
        ),
    ]
