# Generated by Django 2.0.13 on 2019-06-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0030_auto_20190618_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_cast_total_facebook_likes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_content_rate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_facenumber_in_poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_num_critc_for_review',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_num_user_for_reviews',
        ),
    ]
