# Generated by Django 2.0.13 on 2019-06-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0031_auto_20190618_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_cast_total_facebook_likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_content_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.ContentRate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_facenumber_in_poster',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_num_critc_for_review',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_num_user_for_reviews',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
