# Generated by Django 2.0.13 on 2019-06-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0032_auto_20190618_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=200)),
            ],
        ),
    ]
