# Generated by Django 2.0.13 on 2019-06-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0033_actormovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actormovies',
            name='actor_name',
        ),
        migrations.AddField(
            model_name='actormovies',
            name='actor_facebook_likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actormovies',
            name='actor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.Actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actormovies',
            name='movie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie'),
            preserve_default=False,
        ),
    ]
