# Generated by Django 2.0.13 on 2019-06-19 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0034_auto_20190618_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actormovies',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='actormovies',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_actor_1_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.Actor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ActorMovies',
        ),
    ]
