# Generated by Django 2.0.13 on 2019-06-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0036_movie_movie_actor_1_facebook_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_actor_1_facebook_likes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_actor_1_name',
        ),
    ]
