# Generated by Django 2.0.13 on 2019-06-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0038_movieactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id_plot', models.AutoField(primary_key=True, serialize=False)),
                ('plot_name', models.CharField(max_length=200)),
            ],
        ),
    ]
