# Generated by Django 2.0.13 on 2019-06-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0039_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Plot')),
            ],
        ),
    ]
