# Generated by Django 2.0.13 on 2019-06-20 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0040_plotmovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotmovie',
            name='id_actor',
        ),
        migrations.AddField(
            model_name='plotmovie',
            name='id_plot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.Plot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plotmovie',
            name='id_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie'),
        ),
    ]
