# Generated by Django 2.0.13 on 2019-06-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0041_auto_20190619_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_genres',
            field=models.ManyToManyField(to='Movies.Plot'),
        ),
    ]
